[build]
  command = "pip install -r requirements.txt && npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 